### ISSUE TITLE
show edit/delete button onHover

### ISSUE THREAD

**Issue by rpollock03** [IonicaBizau/react-todo-app#10]
Hi @IonicaBizau This is a design issue. It looks messy having the 'edit' and 'delete' buttons always visible for every todo. It would be better to have these buttons displayed when the user hovers over a todo. If you agree, please assign to me and I will add this feature. I'm new to github and trying to complete my hacktoberfest challenge! Many thanks to you.

**Comment by IonicaBizau** [comment]
That would be great! ❇️
