### ISSUE TITLE
Dark Them 

### ISSUE THREAD

**Issue by ashishsiot** [IonicaBizau/react-todo-app#11]
Can We Add Dark Mode On This To Do Web Project.

**Comment by IonicaBizau** [comment]
Yes, of course! Feel free to contribute!
It could be a select box to choose the theme or so.

**Comment by ashishsiot** [comment]
> Yes, of course! Feel free to contribute! It could be a select box to choose the theme or so.
> […](#)
> Sent from my iPhone
> On 2 Dec 2020, at 19:44, Ashish Bhoir ***@***.***> wrote: ﻿ Can We Add Dark Mode On This To Do Web Project. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thank You For Your Replay  😃
